### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lenardjombo**
Added a react open source  project to contribute to.

### CODE REVIEW

**Comment by lenardjombo** [comment]
Added a react open source project to contribute to.

**Comment by lenardjombo** [comment]
Added a react open source project to contribute to

**Comment by lenardjombo** [comment]
react open source projects

**Comment by lenardjombo** [comment]
nice

**Comment by Dun-sin** [comment]
Sorry this project doesn't reach the project requirements, try another, but make sure to read the contributing file first

**Comment by lenardjombo** [comment]
Okay..Thanks

**Pull request closed without merging**
